### ISSUE TITLE
Filelink visibility "protected" looks useless

### ISSUE THREAD

**Issue by tom93** [NZOI/nztrain#106]
The visibility of filelinks can be set to "protected", which allows users to view the file if they are not currently competing (see [app/models/filelink.rb:17](https://github.com/NZOI/nztrain/blob/843d01e5a25965046fc06742beb615878065d11e/app/models/filelink.rb#L17), [app/policies/filelink_policy.rb:26](https://github.com/NZOI/nztrain/blob/843d01e5a25965046fc06742beb615878065d11e/app/policies/filelink_policy.rb#L26)).
I don't understand what this is for.

The problem series importer sets the visibility of problem statement attachments to "protected" (see [app/workers/problem_series/import_worker.rb:254](https://github.com/NZOI/nztrain/blob/843d01e5a25965046fc06742beb615878065d11e/app/workers/problem_series/import_worker.rb#L254)), but I think the intention there is for the statement to be visible only if the user *is* currently competing. (Fortunately, this doesn't expose the problem statements before the competition because the controller also checks that the containing problem is accessible, see [app/controllers/filelinks/roots_controller.rb:51](https://github.com/NZOI/nztrain/blob/843d01e5a25965046fc06742beb615878065d11e/app/controllers/filelinks/roots_controller.rb#L51:L63).)

I thought it might be to do with closed-book exams, but that doesn't make sense either because the policy doesn't check if the contest is closed book or open book.

Does anyone have any insights as to what "protected" is meant for?
If not, I propose that we remove "protected" (and change the problem series importer to use "public").

**Comment by Holmes98** [comment]
> I thought it might be to do with closed-book exams, but that doesn't make sense either because the policy doesn't check if the contest is closed book or open book.

I think the intention *is* actually to prevent access to file attachments of other problems during closed-book contests (the functionality to choose which type doesn't seem to be implemented, so all contests are closed-book at the moment). But as you said, the problem authorization already handles this, and it doesn't work if a contest problem has protected file (since it disallows access to competing users), so it doesn't seem too useful.

The only case I can think of where it could potentially be useful is for file attachments in groups – in that case, `public` files would be visible, but `protected` files would not during a contest.

Whether we keep it or not (I'm undecided), I do agree with changing the importer to use `public`.

**Comment by tom93** [comment]
Import worker fixed in #112.
Closing because it makes sense to use 'protected' for file attachments in groups to hide them during a contest.
